services:
  - type: web
    name: finvision
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 20
    autoDeploy: true
