export const ECONOMIC_EVENTS = [
  // May 2026
  { date: '2026-05-05', time: '2:00 PM ET',  name: 'FOMC Meeting Day 1',          category: 'Fed Policy',   importance: 'High',   forecast: null,           previous: '4.25–4.50%' },
  { date: '2026-05-06', time: '2:00 PM ET',  name: 'FOMC Rate Decision',          category: 'Fed Policy',   importance: 'High',   forecast: '4.25–4.50%',   previous: '4.25–4.50%' },
  { date: '2026-05-06', time: '2:30 PM ET',  name: 'Fed Chair Press Conference',  category: 'Fed Policy',   importance: 'High',   forecast: null,           previous: null },
  { date: '2026-05-08', time: '8:30 AM ET',  name: 'Nonfarm Payrolls',            category: 'Employment',   importance: 'High',   forecast: '+185K',        previous: '+228K' },
  { date: '2026-05-08', time: '8:30 AM ET',  name: 'Unemployment Rate',           category: 'Employment',   importance: 'High',   forecast: '4.1%',         previous: '4.2%' },
  { date: '2026-05-08', time: '8:30 AM ET',  name: 'Avg Hourly Earnings (MoM)',   category: 'Employment',   importance: 'Medium', forecast: '+0.3%',        previous: '+0.3%' },
  { date: '2026-05-13', time: '8:30 AM ET',  name: 'CPI (MoM)',                   category: 'Inflation',    importance: 'High',   forecast: '+0.3%',        previous: '+0.2%' },
  { date: '2026-05-13', time: '8:30 AM ET',  name: 'Core CPI (YoY)',              category: 'Inflation',    importance: 'High',   forecast: '+3.1%',        previous: '+3.0%' },
  { date: '2026-05-14', time: '8:30 AM ET',  name: 'PPI (MoM)',                   category: 'Inflation',    importance: 'Medium', forecast: '+0.2%',        previous: '+0.1%' },
  { date: '2026-05-15', time: '8:30 AM ET',  name: 'Retail Sales (MoM)',          category: 'Consumer',     importance: 'Medium', forecast: '+0.4%',        previous: '+0.6%' },
  { date: '2026-05-15', time: '8:30 AM ET',  name: 'Initial Jobless Claims',      category: 'Employment',   importance: 'Medium', forecast: '215K',         previous: '220K' },
  { date: '2026-05-16', time: '10:00 AM ET', name: 'Consumer Sentiment (UoM)',    category: 'Consumer',     importance: 'Low',    forecast: '72.0',         previous: '71.5' },
  { date: '2026-05-22', time: '8:30 AM ET',  name: 'Initial Jobless Claims',      category: 'Employment',   importance: 'Medium', forecast: '213K',         previous: '215K' },
  { date: '2026-05-22', time: '10:00 AM ET', name: 'Existing Home Sales',         category: 'Housing',      importance: 'Low',    forecast: '4.10M',        previous: '4.02M' },
  { date: '2026-05-27', time: '10:00 AM ET', name: 'Consumer Confidence (CB)',    category: 'Consumer',     importance: 'Medium', forecast: '98.5',         previous: '97.2' },
  { date: '2026-05-27', time: '10:00 AM ET', name: 'New Home Sales',              category: 'Housing',      importance: 'Low',    forecast: '685K',         previous: '672K' },
  { date: '2026-05-29', time: '8:30 AM ET',  name: 'GDP (Q1 2nd Estimate)',       category: 'Growth',       importance: 'High',   forecast: '+2.2%',        previous: '+2.4%' },
  { date: '2026-05-30', time: '8:30 AM ET',  name: 'PCE Price Index (MoM)',       category: 'Inflation',    importance: 'High',   forecast: '+0.3%',        previous: '+0.3%' },
  { date: '2026-05-30', time: '8:30 AM ET',  name: 'Core PCE (YoY)',              category: 'Inflation',    importance: 'High',   forecast: '+2.6%',        previous: '+2.6%' },
  // June 2026
  { date: '2026-06-02', time: '10:00 AM ET', name: 'ISM Manufacturing PMI',       category: 'Manufacturing',importance: 'Medium', forecast: '49.5',         previous: '49.0' },
  { date: '2026-06-04', time: '10:00 AM ET', name: 'ISM Services PMI',            category: 'Services',     importance: 'Medium', forecast: '51.2',         previous: '50.8' },
  { date: '2026-06-05', time: '8:30 AM ET',  name: 'Nonfarm Payrolls',            category: 'Employment',   importance: 'High',   forecast: '+175K',        previous: '+185K' },
  { date: '2026-06-05', time: '8:30 AM ET',  name: 'Unemployment Rate',           category: 'Employment',   importance: 'High',   forecast: '4.1%',         previous: '4.1%' },
  { date: '2026-06-10', time: '8:30 AM ET',  name: 'CPI (MoM)',                   category: 'Inflation',    importance: 'High',   forecast: '+0.2%',        previous: '+0.3%' },
  { date: '2026-06-10', time: '8:30 AM ET',  name: 'Core CPI (YoY)',              category: 'Inflation',    importance: 'High',   forecast: '+3.0%',        previous: '+3.1%' },
  { date: '2026-06-11', time: '8:30 AM ET',  name: 'PPI (MoM)',                   category: 'Inflation',    importance: 'Medium', forecast: '+0.2%',        previous: '+0.2%' },
  { date: '2026-06-12', time: '8:30 AM ET',  name: 'Initial Jobless Claims',      category: 'Employment',   importance: 'Medium', forecast: '218K',         previous: '213K' },
  { date: '2026-06-16', time: '8:30 AM ET',  name: 'Retail Sales (MoM)',          category: 'Consumer',     importance: 'Medium', forecast: '+0.3%',        previous: '+0.4%' },
  { date: '2026-06-17', time: '2:00 PM ET',  name: 'FOMC Rate Decision',          category: 'Fed Policy',   importance: 'High',   forecast: '4.00–4.25%',   previous: '4.25–4.50%' },
  { date: '2026-06-17', time: '2:30 PM ET',  name: 'Fed Chair Press Conference',  category: 'Fed Policy',   importance: 'High',   forecast: null,           previous: null },
  { date: '2026-06-19', time: '8:30 AM ET',  name: 'Initial Jobless Claims',      category: 'Employment',   importance: 'Medium', forecast: '216K',         previous: '218K' },
  { date: '2026-06-24', time: '10:00 AM ET', name: 'Consumer Confidence (CB)',    category: 'Consumer',     importance: 'Medium', forecast: '99.0',         previous: '98.5' },
  { date: '2026-06-26', time: '8:30 AM ET',  name: 'GDP (Q1 3rd Estimate)',       category: 'Growth',       importance: 'Medium', forecast: '+2.1%',        previous: '+2.2%' },
  { date: '2026-06-27', time: '8:30 AM ET',  name: 'PCE Price Index (MoM)',       category: 'Inflation',    importance: 'High',   forecast: '+0.2%',        previous: '+0.3%' },
  { date: '2026-06-27', time: '8:30 AM ET',  name: 'Core PCE (YoY)',              category: 'Inflation',    importance: 'High',   forecast: '+2.5%',        previous: '+2.6%' },
  // July 2026
  { date: '2026-07-01', time: '10:00 AM ET', name: 'ISM Manufacturing PMI',       category: 'Manufacturing',importance: 'Medium', forecast: '50.0',         previous: '49.5' },
  { date: '2026-07-03', time: '10:00 AM ET', name: 'ISM Services PMI',            category: 'Services',     importance: 'Medium', forecast: '51.5',         previous: '51.2' },
  { date: '2026-07-10', time: '8:30 AM ET',  name: 'Nonfarm Payrolls',            category: 'Employment',   importance: 'High',   forecast: '+180K',        previous: '+175K' },
  { date: '2026-07-10', time: '8:30 AM ET',  name: 'Unemployment Rate',           category: 'Employment',   importance: 'High',   forecast: '4.0%',         previous: '4.1%' },
  { date: '2026-07-14', time: '8:30 AM ET',  name: 'CPI (MoM)',                   category: 'Inflation',    importance: 'High',   forecast: '+0.2%',        previous: '+0.2%' },
  { date: '2026-07-14', time: '8:30 AM ET',  name: 'Core CPI (YoY)',              category: 'Inflation',    importance: 'High',   forecast: '+2.9%',        previous: '+3.0%' },
  { date: '2026-07-15', time: '8:30 AM ET',  name: 'PPI (MoM)',                   category: 'Inflation',    importance: 'Medium', forecast: '+0.1%',        previous: '+0.2%' },
  { date: '2026-07-16', time: '8:30 AM ET',  name: 'Initial Jobless Claims',      category: 'Employment',   importance: 'Medium', forecast: '210K',         previous: '215K' },
  { date: '2026-07-17', time: '8:30 AM ET',  name: 'Retail Sales (MoM)',          category: 'Consumer',     importance: 'Medium', forecast: '+0.3%',        previous: '+0.3%' },
  { date: '2026-07-17', time: '10:00 AM ET', name: 'Consumer Sentiment (UoM)',    category: 'Consumer',     importance: 'Low',    forecast: '73.5',         previous: '72.0' },
  { date: '2026-07-25', time: '10:00 AM ET', name: 'Consumer Confidence (CB)',    category: 'Consumer',     importance: 'Medium', forecast: '100.0',        previous: '99.0' },
  { date: '2026-07-28', time: '2:00 PM ET',  name: 'FOMC Rate Decision',          category: 'Fed Policy',   importance: 'High',   forecast: '4.00–4.25%',   previous: '4.00–4.25%' },
  { date: '2026-07-28', time: '2:30 PM ET',  name: 'Fed Chair Press Conference',  category: 'Fed Policy',   importance: 'High',   forecast: null,           previous: null },
  { date: '2026-07-30', time: '8:30 AM ET',  name: 'GDP (Q2 Advance Estimate)',   category: 'Growth',       importance: 'High',   forecast: '+2.5%',        previous: '+2.1%' },
  { date: '2026-07-31', time: '8:30 AM ET',  name: 'PCE Price Index (MoM)',       category: 'Inflation',    importance: 'High',   forecast: '+0.2%',        previous: '+0.2%' },
  { date: '2026-07-31', time: '8:30 AM ET',  name: 'Core PCE (YoY)',              category: 'Inflation',    importance: 'High',   forecast: '+2.4%',        previous: '+2.5%' },
  // August 2026
  { date: '2026-08-05', time: '10:00 AM ET', name: 'ISM Services PMI',            category: 'Services',     importance: 'Medium', forecast: '51.8',         previous: '51.5' },
  { date: '2026-08-07', time: '8:30 AM ET',  name: 'Nonfarm Payrolls',            category: 'Employment',   importance: 'High',   forecast: '+190K',        previous: '+180K' },
  { date: '2026-08-07', time: '8:30 AM ET',  name: 'Unemployment Rate',           category: 'Employment',   importance: 'High',   forecast: '4.0%',         previous: '4.0%' },
  { date: '2026-08-12', time: '8:30 AM ET',  name: 'CPI (MoM)',                   category: 'Inflation',    importance: 'High',   forecast: '+0.2%',        previous: '+0.2%' },
  { date: '2026-08-12', time: '8:30 AM ET',  name: 'Core CPI (YoY)',              category: 'Inflation',    importance: 'High',   forecast: '+2.8%',        previous: '+2.9%' },
  { date: '2026-08-13', time: '8:30 AM ET',  name: 'PPI (MoM)',                   category: 'Inflation',    importance: 'Medium', forecast: '+0.1%',        previous: '+0.1%' },
  { date: '2026-08-14', time: '8:30 AM ET',  name: 'Initial Jobless Claims',      category: 'Employment',   importance: 'Medium', forecast: '208K',         previous: '210K' },
  { date: '2026-08-15', time: '8:30 AM ET',  name: 'Retail Sales (MoM)',          category: 'Consumer',     importance: 'Medium', forecast: '+0.4%',        previous: '+0.3%' },
  { date: '2026-08-27', time: '10:00 AM ET', name: 'Consumer Confidence (CB)',    category: 'Consumer',     importance: 'Medium', forecast: '101.0',        previous: '100.0' },
  { date: '2026-08-28', time: '8:30 AM ET',  name: 'GDP (Q2 2nd Estimate)',       category: 'Growth',       importance: 'Medium', forecast: '+2.4%',        previous: '+2.5%' },
  { date: '2026-08-29', time: '8:30 AM ET',  name: 'PCE Price Index (MoM)',       category: 'Inflation',    importance: 'High',   forecast: '+0.2%',        previous: '+0.2%' },
];

export const IMPORTANCE_CONFIG = {
  High:   { badge: 'text-red-400 bg-red-500/10 border border-red-500/20',              dot: 'bg-red-500',    label: 'High'   },
  Medium: { badge: 'text-yellow-400 bg-yellow-500/10 border border-yellow-500/20',     dot: 'bg-yellow-500', label: 'Medium' },
  Low:    { badge: 'text-gray-400 bg-gray-500/10 border border-gray-500/20',           dot: 'bg-gray-500',   label: 'Low'    },
};

export const CATEGORY_ICONS = {
  'Fed Policy':    '🏦',
  'Inflation':     '📈',
  'Employment':    '👥',
  'Growth':        '📊',
  'Consumer':      '🛒',
  'Manufacturing': '🏭',
  'Services':      '💼',
  'Housing':       '🏠',
};
