export const ETF_SET = new Set([
  'SPY','QQQ','DIA','IWM','VTI','VOO','ARKK',
  // Sector ETFs
  'XLF','XLK','XLE','XLV','XLY','XLP','XLI','XLB','XLU','XLRE','XLC',
  // Commodity ETFs
  'GLD','SLV','IAU','USO','UNG','PDBC','DBC',
  'AGG','TLT','HYG',
  // Leveraged bull
  'TQQQ','UPRO','SPXL','TECL','UDOW','TNA','SOXL','FNGU','FAS','LABU','NAIL','BULZ',
  // Leveraged bear
  'SQQQ','SPXU','SPXS','TECS','SDOW','TZA','SOXS','FNGD','FAZ','LABD',
  // Volatility
  'UVXY','SVXY',
  // International — developed & emerging
  'EFA','EEM','VEU','VWO','IEFA','VGK','EWJ','EWZ','FXI','IEMG',
  // International — country-specific
  'INDA','MCHI','EWY','EWA','EWT','KWEB',
  // Crypto exposure
  'IBIT','FBTC','GBTC','BITB','BITO','ETHA','MSTR',
]);

export const ETF_INFO = {
  SPY: {
    fullName: 'SPDR S&P 500 ETF Trust',
    issuer: 'State Street',
    expenseRatio: 0.0945,
    aum: '$578B',
    index: 'S&P 500',
    category: 'Large Cap Blend',
    inception: '1993-01-22',
    holdings: [
      { symbol: 'AAPL',  name: 'Apple Inc.',             weight: 7.15 },
      { symbol: 'MSFT',  name: 'Microsoft Corp.',         weight: 6.38 },
      { symbol: 'NVDA',  name: 'NVIDIA Corp.',            weight: 5.92 },
      { symbol: 'AMZN',  name: 'Amazon.com Inc.',         weight: 3.77 },
      { symbol: 'META',  name: 'Meta Platforms',          weight: 2.60 },
      { symbol: 'GOOGL', name: 'Alphabet Inc. A',         weight: 2.09 },
      { symbol: 'GOOG',  name: 'Alphabet Inc. C',         weight: 1.76 },
      { symbol: 'TSLA',  name: 'Tesla Inc.',              weight: 1.90 },
      { symbol: 'BRK.B', name: 'Berkshire Hathaway B',   weight: 1.73 },
      { symbol: 'AVGO',  name: 'Broadcom Inc.',           weight: 1.65 },
    ],
    sectors: [
      { name: 'Technology',       weight: 32.1, color: '#6366f1' },
      { name: 'Financials',       weight: 13.2, color: '#22c55e' },
      { name: 'Healthcare',       weight: 11.8, color: '#f59e0b' },
      { name: 'Consumer Disc.',   weight: 10.4, color: '#ec4899' },
      { name: 'Communication',    weight:  8.9, color: '#14b8a6' },
      { name: 'Industrials',      weight:  8.5, color: '#f97316' },
      { name: 'Consumer Staples', weight:  5.8, color: '#8b5cf6' },
      { name: 'Energy',           weight:  3.8, color: '#eab308' },
      { name: 'Other',            weight:  5.5, color: '#6b7280' },
    ],
  },
  QQQ: {
    fullName: 'Invesco QQQ Trust',
    issuer: 'Invesco',
    expenseRatio: 0.20,
    aum: '$310B',
    index: 'NASDAQ-100',
    category: 'Large Cap Growth',
    inception: '1999-03-10',
    holdings: [
      { symbol: 'AAPL',  name: 'Apple Inc.',         weight: 9.10 },
      { symbol: 'MSFT',  name: 'Microsoft Corp.',     weight: 8.20 },
      { symbol: 'NVDA',  name: 'NVIDIA Corp.',        weight: 7.86 },
      { symbol: 'AMZN',  name: 'Amazon.com Inc.',     weight: 5.21 },
      { symbol: 'META',  name: 'Meta Platforms',      weight: 4.88 },
      { symbol: 'GOOGL', name: 'Alphabet Inc. A',     weight: 2.63 },
      { symbol: 'GOOG',  name: 'Alphabet Inc. C',     weight: 2.51 },
      { symbol: 'TSLA',  name: 'Tesla Inc.',          weight: 2.72 },
      { symbol: 'AVGO',  name: 'Broadcom Inc.',       weight: 2.41 },
      { symbol: 'COST',  name: 'Costco Wholesale',    weight: 2.37 },
    ],
    sectors: [
      { name: 'Technology',     weight: 59.5, color: '#6366f1' },
      { name: 'Communication',  weight: 17.4, color: '#14b8a6' },
      { name: 'Consumer Disc.', weight: 13.5, color: '#ec4899' },
      { name: 'Healthcare',     weight:  5.2, color: '#f59e0b' },
      { name: 'Industrials',    weight:  2.4, color: '#f97316' },
      { name: 'Other',          weight:  2.0, color: '#6b7280' },
    ],
  },
  DIA: {
    fullName: 'SPDR Dow Jones Industrial Average ETF',
    issuer: 'State Street',
    expenseRatio: 0.16,
    aum: '$36B',
    index: 'Dow Jones Industrial Average',
    category: 'Large Cap Blend',
    inception: '1998-01-14',
    holdings: [
      { symbol: 'GS',   name: 'Goldman Sachs',         weight: 8.10 },
      { symbol: 'UNH',  name: 'UnitedHealth Group',    weight: 7.80 },
      { symbol: 'MSFT', name: 'Microsoft Corp.',        weight: 6.40 },
      { symbol: 'HD',   name: 'Home Depot',             weight: 5.90 },
      { symbol: 'CAT',  name: 'Caterpillar Inc.',       weight: 5.20 },
      { symbol: 'AMGN', name: 'Amgen Inc.',             weight: 4.90 },
      { symbol: 'V',    name: 'Visa Inc.',              weight: 4.80 },
      { symbol: 'SHW',  name: 'Sherwin-Williams',       weight: 4.60 },
      { symbol: 'MCD',  name: 'McDonald\'s Corp.',      weight: 4.40 },
      { symbol: 'AXP',  name: 'American Express',       weight: 4.30 },
    ],
    sectors: [
      { name: 'Technology',       weight: 23.0, color: '#6366f1' },
      { name: 'Financials',       weight: 20.5, color: '#22c55e' },
      { name: 'Healthcare',       weight: 16.2, color: '#f59e0b' },
      { name: 'Consumer Disc.',   weight: 14.8, color: '#ec4899' },
      { name: 'Industrials',      weight: 14.3, color: '#f97316' },
      { name: 'Other',            weight: 11.2, color: '#6b7280' },
    ],
  },
  IWM: {
    fullName: 'iShares Russell 2000 ETF',
    issuer: 'BlackRock',
    expenseRatio: 0.19,
    aum: '$65B',
    index: 'Russell 2000',
    category: 'Small Cap Blend',
    inception: '2000-05-22',
    holdings: [
      { symbol: 'SMCI', name: 'Super Micro Computer', weight: 0.65 },
      { symbol: 'MSTR', name: 'MicroStrategy',        weight: 0.58 },
      { symbol: 'COTY', name: 'Coty Inc.',            weight: 0.52 },
      { symbol: 'RIVN', name: 'Rivian Automotive',    weight: 0.48 },
      { symbol: 'PLUG', name: 'Plug Power Inc.',      weight: 0.42 },
      { symbol: 'HIMS', name: 'Hims & Hers Health',   weight: 0.40 },
      { symbol: 'BILI', name: 'Bilibili Inc.',        weight: 0.38 },
      { symbol: 'JOBY', name: 'Joby Aviation',        weight: 0.35 },
      { symbol: 'IQ',   name: 'iQIYI Inc.',           weight: 0.32 },
      { symbol: 'JANX', name: 'Janux Therapeutics',   weight: 0.31 },
    ],
    sectors: [
      { name: 'Healthcare',       weight: 17.8, color: '#f59e0b' },
      { name: 'Financials',       weight: 17.2, color: '#22c55e' },
      { name: 'Industrials',      weight: 15.9, color: '#f97316' },
      { name: 'Technology',       weight: 14.8, color: '#6366f1' },
      { name: 'Consumer Disc.',   weight: 11.4, color: '#ec4899' },
      { name: 'Energy',           weight:  6.0, color: '#eab308' },
      { name: 'Other',            weight: 16.9, color: '#6b7280' },
    ],
  },
  VTI: {
    fullName: 'Vanguard Total Stock Market ETF',
    issuer: 'Vanguard',
    expenseRatio: 0.03,
    aum: '$460B',
    index: 'CRSP US Total Market',
    category: 'Total Market',
    inception: '2001-05-24',
    holdings: [
      { symbol: 'AAPL',  name: 'Apple Inc.',         weight: 6.30 },
      { symbol: 'MSFT',  name: 'Microsoft Corp.',    weight: 5.60 },
      { symbol: 'NVDA',  name: 'NVIDIA Corp.',       weight: 5.20 },
      { symbol: 'AMZN',  name: 'Amazon.com Inc.',    weight: 3.31 },
      { symbol: 'META',  name: 'Meta Platforms',     weight: 2.28 },
      { symbol: 'GOOGL', name: 'Alphabet Inc. A',    weight: 1.84 },
      { symbol: 'TSLA',  name: 'Tesla Inc.',         weight: 1.68 },
      { symbol: 'GOOG',  name: 'Alphabet Inc. C',    weight: 1.55 },
      { symbol: 'BRK.B', name: 'Berkshire Hathaway', weight: 1.52 },
      { symbol: 'AVGO',  name: 'Broadcom Inc.',      weight: 1.45 },
    ],
    sectors: [
      { name: 'Technology',       weight: 30.1, color: '#6366f1' },
      { name: 'Consumer Disc.',   weight: 14.7, color: '#ec4899' },
      { name: 'Industrials',      weight: 13.2, color: '#f97316' },
      { name: 'Healthcare',       weight: 12.5, color: '#f59e0b' },
      { name: 'Financials',       weight: 12.0, color: '#22c55e' },
      { name: 'Other',            weight: 17.5, color: '#6b7280' },
    ],
  },
  VOO: {
    fullName: 'Vanguard S&P 500 ETF',
    issuer: 'Vanguard',
    expenseRatio: 0.03,
    aum: '$550B',
    index: 'S&P 500',
    category: 'Large Cap Blend',
    inception: '2010-09-07',
    holdings: [
      { symbol: 'AAPL',  name: 'Apple Inc.',         weight: 7.20 },
      { symbol: 'MSFT',  name: 'Microsoft Corp.',    weight: 6.41 },
      { symbol: 'NVDA',  name: 'NVIDIA Corp.',       weight: 5.95 },
      { symbol: 'AMZN',  name: 'Amazon.com Inc.',    weight: 3.79 },
      { symbol: 'META',  name: 'Meta Platforms',     weight: 2.62 },
      { symbol: 'GOOGL', name: 'Alphabet Inc. A',    weight: 2.10 },
      { symbol: 'GOOG',  name: 'Alphabet Inc. C',    weight: 1.77 },
      { symbol: 'TSLA',  name: 'Tesla Inc.',         weight: 1.91 },
      { symbol: 'BRK.B', name: 'Berkshire Hathaway', weight: 1.74 },
      { symbol: 'AVGO',  name: 'Broadcom Inc.',      weight: 1.66 },
    ],
    sectors: [
      { name: 'Technology',       weight: 32.1, color: '#6366f1' },
      { name: 'Financials',       weight: 13.2, color: '#22c55e' },
      { name: 'Healthcare',       weight: 11.8, color: '#f59e0b' },
      { name: 'Consumer Disc.',   weight: 10.4, color: '#ec4899' },
      { name: 'Communication',    weight:  8.9, color: '#14b8a6' },
      { name: 'Other',            weight: 23.6, color: '#6b7280' },
    ],
  },
  GLD: {
    fullName: 'SPDR Gold Shares',
    issuer: 'State Street',
    expenseRatio: 0.40,
    aum: '$74B',
    index: 'Gold Spot Price',
    category: 'Commodities — Gold',
    inception: '2004-11-18',
    holdings: [{ symbol: 'GOLD', name: 'Physical Gold Bullion', weight: 100 }],
    sectors: [{ name: 'Gold', weight: 100, color: '#eab308' }],
  },
  USO: {
    fullName: 'United States Oil Fund',
    issuer: 'USCF Investments',
    expenseRatio: 0.60,
    aum: '$1.2B',
    index: 'WTI Crude Oil Futures',
    category: 'Commodities — Oil',
    inception: '2006-04-10',
    holdings: [{ symbol: 'CL', name: 'WTI Crude Oil Futures', weight: 100 }],
    sectors: [{ name: 'Energy', weight: 100, color: '#f97316' }],
  },
  XLF: {
    fullName: 'Financial Select Sector SPDR Fund',
    issuer: 'State Street',
    expenseRatio: 0.09,
    aum: '$42B',
    index: 'S&P 500 Financials Sector',
    category: 'Sector — Financials',
    inception: '1998-12-16',
    holdings: [
      { symbol: 'BRK.B', name: 'Berkshire Hathaway B', weight: 13.10 },
      { symbol: 'JPM',   name: 'JPMorgan Chase',       weight: 12.50 },
      { symbol: 'V',     name: 'Visa Inc.',            weight: 8.20  },
      { symbol: 'MA',    name: 'Mastercard Inc.',      weight: 6.90  },
      { symbol: 'BAC',   name: 'Bank of America',      weight: 4.60  },
      { symbol: 'GS',    name: 'Goldman Sachs',        weight: 3.80  },
      { symbol: 'WFC',   name: 'Wells Fargo',          weight: 3.70  },
      { symbol: 'MS',    name: 'Morgan Stanley',       weight: 3.20  },
      { symbol: 'AXP',   name: 'American Express',     weight: 3.10  },
      { symbol: 'SPGI',  name: 'S&P Global Inc.',      weight: 2.90  },
    ],
    sectors: [{ name: 'Financials', weight: 100, color: '#22c55e' }],
  },
  XLK: {
    fullName: 'Technology Select Sector SPDR Fund',
    issuer: 'State Street',
    expenseRatio: 0.09,
    aum: '$70B',
    index: 'S&P 500 Technology Sector',
    category: 'Sector — Technology',
    inception: '1998-12-16',
    holdings: [
      { symbol: 'AAPL',  name: 'Apple Inc.',       weight: 22.50 },
      { symbol: 'MSFT',  name: 'Microsoft Corp.',  weight: 21.80 },
      { symbol: 'NVDA',  name: 'NVIDIA Corp.',     weight: 18.60 },
      { symbol: 'AVGO',  name: 'Broadcom Inc.',    weight:  5.20 },
      { symbol: 'AMD',   name: 'AMD',              weight:  3.40 },
      { symbol: 'ORCL',  name: 'Oracle Corp.',     weight:  3.20 },
      { symbol: 'QCOM',  name: 'Qualcomm Inc.',    weight:  2.80 },
      { symbol: 'TXN',   name: 'Texas Instruments', weight: 2.60 },
      { symbol: 'AMAT',  name: 'Applied Materials', weight: 2.40 },
      { symbol: 'INTC',  name: 'Intel Corp.',       weight: 2.10 },
    ],
    sectors: [{ name: 'Technology', weight: 100, color: '#6366f1' }],
  },
  XLE: {
    fullName: 'Energy Select Sector SPDR Fund',
    issuer: 'State Street',
    expenseRatio: 0.09,
    aum: '$35B',
    index: 'S&P 500 Energy Sector',
    category: 'Sector — Energy',
    inception: '1998-12-16',
    holdings: [
      { symbol: 'XOM',  name: 'Exxon Mobil',       weight: 22.10 },
      { symbol: 'CVX',  name: 'Chevron Corp.',      weight: 15.80 },
      { symbol: 'COP',  name: 'ConocoPhillips',     weight:  7.40 },
      { symbol: 'EOG',  name: 'EOG Resources',      weight:  4.50 },
      { symbol: 'SLB',  name: 'Schlumberger',       weight:  4.30 },
      { symbol: 'MPC',  name: 'Marathon Petroleum', weight:  4.10 },
      { symbol: 'PSX',  name: 'Phillips 66',        weight:  3.90 },
      { symbol: 'PXD',  name: 'Pioneer Natural',    weight:  3.60 },
      { symbol: 'OXY',  name: 'Occidental Petroleum', weight: 3.40 },
      { symbol: 'VLO',  name: 'Valero Energy',      weight:  3.20 },
    ],
    sectors: [{ name: 'Energy', weight: 100, color: '#f97316' }],
  },
  XLV: {
    fullName: 'Health Care Select Sector SPDR Fund',
    issuer: 'State Street',
    expenseRatio: 0.09,
    aum: '$38B',
    index: 'S&P 500 Health Care Sector',
    category: 'Sector — Healthcare',
    inception: '1998-12-16',
    holdings: [
      { symbol: 'LLY',  name: 'Eli Lilly',          weight: 13.40 },
      { symbol: 'UNH',  name: 'UnitedHealth Group',  weight: 10.20 },
      { symbol: 'JNJ',  name: 'Johnson & Johnson',   weight:  8.50 },
      { symbol: 'ABT',  name: 'Abbott Laboratories', weight:  4.80 },
      { symbol: 'MRK',  name: 'Merck & Co.',         weight:  4.60 },
      { symbol: 'TMO',  name: 'Thermo Fisher',       weight:  4.40 },
      { symbol: 'AMGN', name: 'Amgen Inc.',           weight:  4.20 },
      { symbol: 'PFE',  name: 'Pfizer Inc.',          weight:  3.80 },
      { symbol: 'ABBV', name: 'AbbVie Inc.',          weight:  3.60 },
      { symbol: 'DHR',  name: 'Danaher Corp.',        weight:  3.40 },
    ],
    sectors: [{ name: 'Healthcare', weight: 100, color: '#f59e0b' }],
  },
  XLY: {
    fullName: 'Consumer Discretionary Select Sector SPDR Fund',
    issuer: 'State Street',
    expenseRatio: 0.09,
    aum: '$19B',
    index: 'S&P 500 Consumer Discretionary',
    category: 'Sector — Consumer Discretionary',
    inception: '1998-12-16',
    holdings: [
      { symbol: 'AMZN', name: 'Amazon.com Inc.',   weight: 22.80 },
      { symbol: 'TSLA', name: 'Tesla Inc.',         weight: 17.40 },
      { symbol: 'HD',   name: 'Home Depot',         weight:  9.10 },
      { symbol: 'MCD',  name: "McDonald's Corp.",   weight:  5.30 },
      { symbol: 'NKE',  name: 'Nike Inc.',          weight:  3.80 },
      { symbol: 'LOW',  name: "Lowe's Companies",   weight:  3.60 },
      { symbol: 'BKNG', name: 'Booking Holdings',   weight:  3.40 },
      { symbol: 'TJX',  name: 'TJX Companies',      weight:  3.10 },
      { symbol: 'CMG',  name: 'Chipotle Mexican',   weight:  2.80 },
      { symbol: 'SBUX', name: 'Starbucks Corp.',    weight:  2.40 },
    ],
    sectors: [{ name: 'Consumer Discretionary', weight: 100, color: '#ec4899' }],
  },
  XLP: {
    fullName: 'Consumer Staples Select Sector SPDR Fund',
    issuer: 'State Street',
    expenseRatio: 0.09,
    aum: '$14B',
    index: 'S&P 500 Consumer Staples',
    category: 'Sector — Consumer Staples',
    inception: '1998-12-16',
    holdings: [
      { symbol: 'PG',   name: 'Procter & Gamble',   weight: 15.40 },
      { symbol: 'KO',   name: 'Coca-Cola Co.',       weight: 10.30 },
      { symbol: 'PEP',  name: 'PepsiCo Inc.',        weight:  9.80 },
      { symbol: 'COST', name: 'Costco Wholesale',    weight:  8.50 },
      { symbol: 'WMT',  name: 'Walmart Inc.',        weight:  8.20 },
      { symbol: 'PM',   name: 'Philip Morris Intl.', weight:  4.60 },
      { symbol: 'MO',   name: 'Altria Group',        weight:  3.80 },
      { symbol: 'MDLZ', name: 'Mondelez Intl.',      weight:  3.40 },
      { symbol: 'CL',   name: 'Colgate-Palmolive',   weight:  3.20 },
      { symbol: 'GIS',  name: 'General Mills',       weight:  2.80 },
    ],
    sectors: [{ name: 'Consumer Staples', weight: 100, color: '#84cc16' }],
  },
  XLI: {
    fullName: 'Industrial Select Sector SPDR Fund',
    issuer: 'State Street',
    expenseRatio: 0.09,
    aum: '$21B',
    index: 'S&P 500 Industrials',
    category: 'Sector — Industrials',
    inception: '1998-12-16',
    holdings: [
      { symbol: 'GE',   name: 'GE Aerospace',        weight:  5.80 },
      { symbol: 'RTX',  name: 'RTX Corp.',            weight:  5.20 },
      { symbol: 'HON',  name: 'Honeywell Intl.',      weight:  4.90 },
      { symbol: 'CAT',  name: 'Caterpillar Inc.',     weight:  4.80 },
      { symbol: 'UPS',  name: 'United Parcel Svc.',   weight:  4.20 },
      { symbol: 'BA',   name: 'Boeing Co.',           weight:  4.10 },
      { symbol: 'LMT',  name: 'Lockheed Martin',      weight:  4.00 },
      { symbol: 'DE',   name: 'Deere & Co.',          weight:  3.80 },
      { symbol: 'MMM',  name: '3M Company',           weight:  3.20 },
      { symbol: 'NSC',  name: 'Norfolk Southern',     weight:  2.90 },
    ],
    sectors: [{ name: 'Industrials', weight: 100, color: '#0ea5e9' }],
  },
  XLB: {
    fullName: 'Materials Select Sector SPDR Fund',
    issuer: 'State Street',
    expenseRatio: 0.09,
    aum: '$7B',
    index: 'S&P 500 Materials',
    category: 'Sector — Materials',
    inception: '1998-12-16',
    holdings: [
      { symbol: 'LIN',  name: 'Linde plc',           weight: 17.30 },
      { symbol: 'SHW',  name: 'Sherwin-Williams',     weight:  8.40 },
      { symbol: 'APD',  name: 'Air Products',         weight:  7.10 },
      { symbol: 'FCX',  name: 'Freeport-McMoRan',     weight:  5.80 },
      { symbol: 'NUE',  name: 'Nucor Corp.',          weight:  5.40 },
      { symbol: 'ECL',  name: 'Ecolab Inc.',          weight:  5.20 },
      { symbol: 'NEM',  name: 'Newmont Corp.',        weight:  4.80 },
      { symbol: 'DOW',  name: 'Dow Inc.',             weight:  4.50 },
      { symbol: 'PPG',  name: 'PPG Industries',       weight:  4.20 },
      { symbol: 'ALB',  name: 'Albemarle Corp.',      weight:  3.60 },
    ],
    sectors: [{ name: 'Materials', weight: 100, color: '#78716c' }],
  },
  XLU: {
    fullName: 'Utilities Select Sector SPDR Fund',
    issuer: 'State Street',
    expenseRatio: 0.09,
    aum: '$13B',
    index: 'S&P 500 Utilities',
    category: 'Sector — Utilities',
    inception: '1998-12-16',
    holdings: [
      { symbol: 'NEE',  name: 'NextEra Energy',       weight: 15.20 },
      { symbol: 'SO',   name: 'Southern Company',     weight:  8.40 },
      { symbol: 'DUK',  name: 'Duke Energy',          weight:  8.10 },
      { symbol: 'AEP',  name: 'American Elec. Power', weight:  5.30 },
      { symbol: 'EXC',  name: 'Exelon Corp.',         weight:  4.80 },
      { symbol: 'PCG',  name: 'PG&E Corp.',           weight:  4.20 },
      { symbol: 'SRE',  name: 'Sempra Energy',        weight:  4.10 },
      { symbol: 'D',    name: 'Dominion Energy',      weight:  4.00 },
      { symbol: 'XEL',  name: 'Xcel Energy',          weight:  3.70 },
      { symbol: 'ETR',  name: 'Entergy Corp.',        weight:  3.40 },
    ],
    sectors: [{ name: 'Utilities', weight: 100, color: '#fbbf24' }],
  },
  XLRE: {
    fullName: 'Real Estate Select Sector SPDR Fund',
    issuer: 'State Street',
    expenseRatio: 0.09,
    aum: '$5B',
    index: 'S&P 500 Real Estate',
    category: 'Sector — Real Estate',
    inception: '2015-10-07',
    holdings: [
      { symbol: 'AMT',  name: 'American Tower',       weight: 11.40 },
      { symbol: 'PLD',  name: 'Prologis Inc.',        weight: 10.80 },
      { symbol: 'CCI',  name: 'Crown Castle',         weight:  7.60 },
      { symbol: 'EQIX', name: 'Equinix Inc.',         weight:  7.20 },
      { symbol: 'PSA',  name: 'Public Storage',       weight:  5.80 },
      { symbol: 'SPG',  name: 'Simon Property',       weight:  5.40 },
      { symbol: 'WELL', name: 'Welltower Inc.',       weight:  5.10 },
      { symbol: 'O',    name: 'Realty Income',        weight:  4.80 },
      { symbol: 'DLR',  name: 'Digital Realty',       weight:  4.60 },
      { symbol: 'EQR',  name: 'Equity Residential',   weight:  3.90 },
    ],
    sectors: [{ name: 'Real Estate', weight: 100, color: '#a78bfa' }],
  },
  XLC: {
    fullName: 'Communication Services Select Sector SPDR Fund',
    issuer: 'State Street',
    expenseRatio: 0.09,
    aum: '$16B',
    index: 'S&P 500 Communication Services',
    category: 'Sector — Communication Services',
    inception: '2018-06-18',
    holdings: [
      { symbol: 'META', name: 'Meta Platforms',       weight: 24.10 },
      { symbol: 'GOOGL',name: 'Alphabet Class A',     weight: 13.20 },
      { symbol: 'GOOG', name: 'Alphabet Class C',     weight: 11.80 },
      { symbol: 'NFLX', name: 'Netflix Inc.',         weight:  5.90 },
      { symbol: 'VZ',   name: 'Verizon Comm.',        weight:  5.40 },
      { symbol: 'T',    name: 'AT&T Inc.',            weight:  5.20 },
      { symbol: 'DIS',  name: 'Walt Disney Co.',      weight:  4.60 },
      { symbol: 'CHTR', name: 'Charter Comm.',        weight:  3.80 },
      { symbol: 'EA',   name: 'Electronic Arts',      weight:  2.90 },
      { symbol: 'TTWO', name: 'Take-Two Interactive', weight:  2.40 },
    ],
    sectors: [{ name: 'Communication Services', weight: 100, color: '#38bdf8' }],
  },
  SLV: {
    fullName: 'iShares Silver Trust',
    issuer: 'BlackRock',
    expenseRatio: 0.50,
    aum: '$12B',
    index: 'Silver Spot Price',
    category: 'Commodities — Silver',
    inception: '2006-04-21',
    holdings: [{ symbol: 'SILVER', name: 'Physical Silver Bullion', weight: 100 }],
    sectors: [{ name: 'Silver', weight: 100, color: '#94a3b8' }],
  },
  IAU: {
    fullName: 'iShares Gold Trust',
    issuer: 'BlackRock',
    expenseRatio: 0.25,
    aum: '$32B',
    index: 'Gold Spot Price',
    category: 'Commodities — Gold',
    inception: '2005-01-21',
    holdings: [{ symbol: 'GOLD', name: 'Physical Gold Bullion', weight: 100 }],
    sectors: [{ name: 'Gold', weight: 100, color: '#eab308' }],
  },
  UNG: {
    fullName: 'United States Natural Gas Fund',
    issuer: 'USCF Investments',
    expenseRatio: 0.60,
    aum: '$0.5B',
    index: 'Henry Hub Natural Gas Futures',
    category: 'Commodities — Natural Gas',
    inception: '2007-04-18',
    holdings: [{ symbol: 'NG', name: 'Natural Gas Futures', weight: 100 }],
    sectors: [{ name: 'Natural Gas', weight: 100, color: '#67e8f9' }],
  },
  PDBC: {
    fullName: 'Invesco Optimum Yield Diversified Commodity Strategy No K-1 ETF',
    issuer: 'Invesco',
    expenseRatio: 0.59,
    aum: '$4B',
    index: 'Diversified Commodity Futures',
    category: 'Commodities — Diversified',
    inception: '2014-11-07',
    holdings: [
      { symbol: 'CL',   name: 'Crude Oil Futures',    weight: 30.0 },
      { symbol: 'NG',   name: 'Natural Gas Futures',  weight: 15.0 },
      { symbol: 'GC',   name: 'Gold Futures',         weight: 15.0 },
      { symbol: 'ZC',   name: 'Corn Futures',         weight: 10.0 },
      { symbol: 'ZS',   name: 'Soybean Futures',      weight: 10.0 },
      { symbol: 'HG',   name: 'Copper Futures',       weight:  8.0 },
      { symbol: 'ZW',   name: 'Wheat Futures',        weight:  7.0 },
      { symbol: 'SI',   name: 'Silver Futures',       weight:  5.0 },
    ],
    sectors: [
      { name: 'Energy',       weight: 45, color: '#f97316' },
      { name: 'Metals',       weight: 20, color: '#eab308' },
      { name: 'Agriculture',  weight: 27, color: '#84cc16' },
      { name: 'Other',        weight:  8, color: '#94a3b8' },
    ],
  },
  DBC: {
    fullName: 'Invesco DB Commodity Index Tracking Fund',
    issuer: 'Invesco',
    expenseRatio: 0.85,
    aum: '$1.8B',
    index: 'DBIQ Optimum Yield Diversified Commodity Index',
    category: 'Commodities — Diversified',
    inception: '2006-02-03',
    holdings: [
      { symbol: 'CL',  name: 'WTI Crude Oil',        weight: 23.0 },
      { symbol: 'HO',  name: 'Heating Oil',           weight: 13.0 },
      { symbol: 'ZC',  name: 'Corn',                  weight: 12.5 },
      { symbol: 'ZW',  name: 'Wheat',                 weight: 12.5 },
      { symbol: 'GC',  name: 'Gold',                  weight: 10.0 },
      { symbol: 'SI',  name: 'Silver',                weight:  5.0 },
      { symbol: 'NG',  name: 'Natural Gas',           weight:  5.5 },
      { symbol: 'SB',  name: 'Sugar',                 weight:  5.0 },
      { symbol: 'ZS',  name: 'Soybeans',              weight:  7.5 },
      { symbol: 'HG',  name: 'Copper',                weight:  6.0 },
    ],
    sectors: [
      { name: 'Energy',       weight: 41.5, color: '#f97316' },
      { name: 'Agriculture',  weight: 37.5, color: '#84cc16' },
      { name: 'Metals',       weight: 21.0, color: '#eab308' },
    ],
  },
  AGG: {
    fullName: 'iShares Core U.S. Aggregate Bond ETF',
    issuer: 'BlackRock',
    expenseRatio: 0.03,
    aum: '$110B',
    index: 'Bloomberg US Aggregate Bond',
    category: 'Bonds — Aggregate',
    inception: '2003-09-22',
    holdings: [
      { symbol: 'UST',  name: 'US Treasuries',           weight: 43.5 },
      { symbol: 'MBS',  name: 'Mortgage-Backed Sec.',    weight: 26.0 },
      { symbol: 'CORP', name: 'Investment-Grade Corp.',  weight: 25.2 },
      { symbol: 'GOVT', name: 'Gov\'t-Related Bonds',    weight:  5.3 },
    ],
    sectors: [
      { name: 'Treasuries',        weight: 43.5, color: '#6366f1' },
      { name: 'Mortgage-Backed',   weight: 26.0, color: '#22c55e' },
      { name: 'Corporate',         weight: 25.2, color: '#f59e0b' },
      { name: 'Gov\'t-Related',    weight:  5.3, color: '#14b8a6' },
    ],
  },
  TLT: {
    fullName: 'iShares 20+ Year Treasury Bond ETF',
    issuer: 'BlackRock',
    expenseRatio: 0.15,
    aum: '$48B',
    index: 'ICE US Treasury 20+ Year',
    category: 'Bonds — Long-Term Treasury',
    inception: '2002-07-22',
    holdings: [{ symbol: 'TREASURY', name: '20+ Year US Treasury Bonds', weight: 100 }],
    sectors: [{ name: 'Long-Term Treasuries', weight: 100, color: '#6366f1' }],
  },
  HYG: {
    fullName: 'iShares iBoxx High Yield Corporate Bond ETF',
    issuer: 'BlackRock',
    expenseRatio: 0.48,
    aum: '$15B',
    index: 'Markit iBoxx USD Liquid High Yield',
    category: 'Bonds — High Yield',
    inception: '2007-04-04',
    holdings: [{ symbol: 'HY', name: 'High Yield Corporate Bonds', weight: 100 }],
    sectors: [
      { name: 'Industrial', weight: 48.5, color: '#f97316' },
      { name: 'Financials', weight: 26.2, color: '#22c55e' },
      { name: 'Utilities',  weight:  8.3, color: '#14b8a6' },
      { name: 'Other',      weight: 17.0, color: '#6b7280' },
    ],
  },
  ARKK: {
    fullName: 'ARK Innovation ETF',
    issuer: 'ARK Invest',
    expenseRatio: 0.75,
    aum: '$6B',
    index: 'Active — Disruptive Innovation',
    category: 'Actively Managed Growth',
    inception: '2014-10-31',
    holdings: [
      { symbol: 'TSLA',  name: 'Tesla Inc.',          weight: 12.50 },
      { symbol: 'ROKU',  name: 'Roku Inc.',           weight:  8.20 },
      { symbol: 'COIN',  name: 'Coinbase Global',     weight:  7.80 },
      { symbol: 'PATH',  name: 'UiPath Inc.',         weight:  6.40 },
      { symbol: 'EXAS',  name: 'Exact Sciences',      weight:  5.90 },
      { symbol: 'BEAM',  name: 'Beam Therapeutics',   weight:  5.20 },
      { symbol: 'TWLO',  name: 'Twilio Inc.',         weight:  4.80 },
      { symbol: 'CRISPR',name: 'CRISPR Therapeutics', weight:  4.60 },
      { symbol: 'TDOC',  name: 'Teladoc Health',      weight:  4.30 },
      { symbol: 'PACB',  name: 'Pacific Biosciences', weight:  3.90 },
    ],
    sectors: [
      { name: 'Technology',      weight: 48.0, color: '#6366f1' },
      { name: 'Healthcare',      weight: 29.0, color: '#f59e0b' },
      { name: 'Consumer Disc.',  weight: 14.0, color: '#ec4899' },
      { name: 'Other',           weight:  9.0, color: '#6b7280' },
    ],
  },
  SQQQ: {
    fullName: 'ProShares UltraPro Short QQQ',
    issuer: 'ProShares',
    expenseRatio: 0.95,
    aum: '$4B',
    index: '3x Inverse NASDAQ-100',
    category: 'Leveraged Inverse',
    inception: '2010-02-09',
    holdings: [{ symbol: 'QQQ', name: 'Short NASDAQ-100 (3x)', weight: 100 }],
    sectors: [{ name: 'Inverse Exposure', weight: 100, color: '#ef4444' }],
  },
  TQQQ: {
    fullName: 'ProShares UltraPro QQQ',
    issuer: 'ProShares',
    expenseRatio: 0.88,
    aum: '$22B',
    index: '3x Leveraged NASDAQ-100',
    category: 'Leveraged',
    inception: '2010-02-09',
    holdings: [{ symbol: 'QQQ', name: 'Long NASDAQ-100 (3x)', weight: 100 }],
    sectors: [{ name: 'Leveraged Long', weight: 100, color: '#22c55e' }],
  },
  UPRO: {
    fullName: 'ProShares UltraPro S&P 500',
    issuer: 'ProShares',
    expenseRatio: 0.91,
    aum: '$3.8B',
    index: '3x Leveraged S&P 500',
    category: 'Leveraged',
    inception: '2009-06-25',
    holdings: [{ symbol: 'SPY', name: 'Long S&P 500 (3x)', weight: 100 }],
    sectors: [{ name: 'Leveraged Long', weight: 100, color: '#22c55e' }],
  },
  SPXL: {
    fullName: 'Direxion Daily S&P 500 Bull 3X Shares',
    issuer: 'Direxion',
    expenseRatio: 0.93,
    aum: '$2.6B',
    index: '3x Leveraged S&P 500',
    category: 'Leveraged',
    inception: '2008-11-05',
    holdings: [{ symbol: 'SPY', name: 'Long S&P 500 (3x)', weight: 100 }],
    sectors: [{ name: 'Leveraged Long', weight: 100, color: '#22c55e' }],
  },
  SPXU: {
    fullName: 'ProShares UltraPro Short S&P 500',
    issuer: 'ProShares',
    expenseRatio: 0.91,
    aum: '$0.9B',
    index: '3x Inverse S&P 500',
    category: 'Leveraged Inverse',
    inception: '2009-06-25',
    holdings: [{ symbol: 'SPY', name: 'Short S&P 500 (3x)', weight: 100 }],
    sectors: [{ name: 'Leveraged Inverse', weight: 100, color: '#ef4444' }],
  },
  SPXS: {
    fullName: 'Direxion Daily S&P 500 Bear 3X Shares',
    issuer: 'Direxion',
    expenseRatio: 0.93,
    aum: '$0.8B',
    index: '3x Inverse S&P 500',
    category: 'Leveraged Inverse',
    inception: '2008-11-05',
    holdings: [{ symbol: 'SPY', name: 'Short S&P 500 (3x)', weight: 100 }],
    sectors: [{ name: 'Leveraged Inverse', weight: 100, color: '#ef4444' }],
  },
  TECL: {
    fullName: 'Direxion Daily Technology Bull 3X Shares',
    issuer: 'Direxion',
    expenseRatio: 0.94,
    aum: '$2.8B',
    index: '3x Leveraged Technology Select Sector',
    category: 'Leveraged',
    inception: '2008-12-17',
    holdings: [{ symbol: 'XLK', name: 'Long Technology Sector (3x)', weight: 100 }],
    sectors: [{ name: 'Leveraged Long', weight: 100, color: '#22c55e' }],
  },
  TECS: {
    fullName: 'Direxion Daily Technology Bear 3X Shares',
    issuer: 'Direxion',
    expenseRatio: 0.94,
    aum: '$0.4B',
    index: '3x Inverse Technology Select Sector',
    category: 'Leveraged Inverse',
    inception: '2008-12-17',
    holdings: [{ symbol: 'XLK', name: 'Short Technology Sector (3x)', weight: 100 }],
    sectors: [{ name: 'Leveraged Inverse', weight: 100, color: '#ef4444' }],
  },
  UDOW: {
    fullName: 'ProShares UltraPro Dow 30',
    issuer: 'ProShares',
    expenseRatio: 0.95,
    aum: '$0.7B',
    index: '3x Leveraged Dow Jones Industrial Average',
    category: 'Leveraged',
    inception: '2010-02-09',
    holdings: [{ symbol: 'DIA', name: 'Long Dow 30 (3x)', weight: 100 }],
    sectors: [{ name: 'Leveraged Long', weight: 100, color: '#22c55e' }],
  },
  SDOW: {
    fullName: 'ProShares UltraPro Short Dow 30',
    issuer: 'ProShares',
    expenseRatio: 0.95,
    aum: '$0.4B',
    index: '3x Inverse Dow Jones Industrial Average',
    category: 'Leveraged Inverse',
    inception: '2010-02-09',
    holdings: [{ symbol: 'DIA', name: 'Short Dow 30 (3x)', weight: 100 }],
    sectors: [{ name: 'Leveraged Inverse', weight: 100, color: '#ef4444' }],
  },
  TNA: {
    fullName: 'Direxion Daily Small Cap Bull 3X Shares',
    issuer: 'Direxion',
    expenseRatio: 1.07,
    aum: '$2.1B',
    index: '3x Leveraged Russell 2000',
    category: 'Leveraged',
    inception: '2008-11-05',
    holdings: [{ symbol: 'IWM', name: 'Long Russell 2000 (3x)', weight: 100 }],
    sectors: [{ name: 'Leveraged Long', weight: 100, color: '#22c55e' }],
  },
  TZA: {
    fullName: 'Direxion Daily Small Cap Bear 3X Shares',
    issuer: 'Direxion',
    expenseRatio: 1.07,
    aum: '$0.4B',
    index: '3x Inverse Russell 2000',
    category: 'Leveraged Inverse',
    inception: '2008-11-05',
    holdings: [{ symbol: 'IWM', name: 'Short Russell 2000 (3x)', weight: 100 }],
    sectors: [{ name: 'Leveraged Inverse', weight: 100, color: '#ef4444' }],
  },
  SOXL: {
    fullName: 'Direxion Daily Semiconductor Bull 3X Shares',
    issuer: 'Direxion',
    expenseRatio: 0.76,
    aum: '$9.2B',
    index: '3x Leveraged PHLX Semiconductor',
    category: 'Leveraged',
    inception: '2010-03-11',
    holdings: [
      { symbol: 'NVDA',  name: 'NVIDIA Corp.',       weight: 22.0 },
      { symbol: 'AVGO',  name: 'Broadcom Inc.',       weight: 14.0 },
      { symbol: 'AMD',   name: 'AMD',                 weight:  8.0 },
      { symbol: 'QCOM',  name: 'Qualcomm Inc.',       weight:  7.5 },
      { symbol: 'TXN',   name: 'Texas Instruments',   weight:  5.5 },
      { symbol: 'AMAT',  name: 'Applied Materials',   weight:  5.0 },
      { symbol: 'INTC',  name: 'Intel Corp.',          weight:  4.5 },
      { symbol: 'MU',    name: 'Micron Technology',   weight:  4.0 },
      { symbol: 'LRCX',  name: 'Lam Research',        weight:  3.5 },
      { symbol: 'KLAC',  name: 'KLA Corp.',            weight:  3.0 },
    ],
    sectors: [{ name: 'Leveraged Long', weight: 100, color: '#22c55e' }],
  },
  SOXS: {
    fullName: 'Direxion Daily Semiconductor Bear 3X Shares',
    issuer: 'Direxion',
    expenseRatio: 0.76,
    aum: '$0.6B',
    index: '3x Inverse PHLX Semiconductor',
    category: 'Leveraged Inverse',
    inception: '2010-03-11',
    holdings: [{ symbol: 'SOX', name: 'Short Semiconductors (3x)', weight: 100 }],
    sectors: [{ name: 'Leveraged Inverse', weight: 100, color: '#ef4444' }],
  },
  FNGU: {
    fullName: 'MicroSectors FANG+ Index 3X Leveraged ETN',
    issuer: 'Bank of Montreal',
    expenseRatio: 0.95,
    aum: '$3.5B',
    index: '3x Leveraged NYSE FANG+ Index',
    category: 'Leveraged',
    inception: '2018-01-22',
    holdings: [
      { symbol: 'META',  name: 'Meta Platforms',   weight: 10.0 },
      { symbol: 'AAPL',  name: 'Apple Inc.',        weight: 10.0 },
      { symbol: 'AMZN',  name: 'Amazon.com Inc.',   weight: 10.0 },
      { symbol: 'NFLX',  name: 'Netflix Inc.',      weight: 10.0 },
      { symbol: 'GOOGL', name: 'Alphabet Inc.',     weight: 10.0 },
      { symbol: 'MSFT',  name: 'Microsoft Corp.',   weight: 10.0 },
      { symbol: 'NVDA',  name: 'NVIDIA Corp.',      weight: 10.0 },
      { symbol: 'TSLA',  name: 'Tesla Inc.',        weight: 10.0 },
      { symbol: 'SNOW',  name: 'Snowflake Inc.',    weight: 10.0 },
      { symbol: 'UBER',  name: 'Uber Technologies', weight: 10.0 },
    ],
    sectors: [{ name: 'Leveraged Long', weight: 100, color: '#22c55e' }],
  },
  FNGD: {
    fullName: 'MicroSectors FANG+ Index -3X Inverse Leveraged ETN',
    issuer: 'Bank of Montreal',
    expenseRatio: 0.95,
    aum: '$0.5B',
    index: '3x Inverse NYSE FANG+ Index',
    category: 'Leveraged Inverse',
    inception: '2018-01-22',
    holdings: [{ symbol: 'FANG+', name: 'Short NYSE FANG+ (3x)', weight: 100 }],
    sectors: [{ name: 'Leveraged Inverse', weight: 100, color: '#ef4444' }],
  },
  FAS: {
    fullName: 'Direxion Daily Financial Bull 3X Shares',
    issuer: 'Direxion',
    expenseRatio: 0.94,
    aum: '$1.8B',
    index: '3x Leveraged Russell 1000 Financial Services',
    category: 'Leveraged',
    inception: '2008-11-06',
    holdings: [{ symbol: 'XLF', name: 'Long Financials (3x)', weight: 100 }],
    sectors: [{ name: 'Leveraged Long', weight: 100, color: '#22c55e' }],
  },
  FAZ: {
    fullName: 'Direxion Daily Financial Bear 3X Shares',
    issuer: 'Direxion',
    expenseRatio: 0.94,
    aum: '$0.3B',
    index: '3x Inverse Russell 1000 Financial Services',
    category: 'Leveraged Inverse',
    inception: '2008-11-06',
    holdings: [{ symbol: 'XLF', name: 'Short Financials (3x)', weight: 100 }],
    sectors: [{ name: 'Leveraged Inverse', weight: 100, color: '#ef4444' }],
  },
  LABU: {
    fullName: 'Direxion Daily S&P Biotech Bull 3X Shares',
    issuer: 'Direxion',
    expenseRatio: 0.94,
    aum: '$1.1B',
    index: '3x Leveraged S&P Biotechnology Select Industry',
    category: 'Leveraged',
    inception: '2015-05-28',
    holdings: [{ symbol: 'XBI', name: 'Long Biotech (3x)', weight: 100 }],
    sectors: [{ name: 'Leveraged Long', weight: 100, color: '#22c55e' }],
  },
  LABD: {
    fullName: 'Direxion Daily S&P Biotech Bear 3X Shares',
    issuer: 'Direxion',
    expenseRatio: 0.94,
    aum: '$0.4B',
    index: '3x Inverse S&P Biotechnology Select Industry',
    category: 'Leveraged Inverse',
    inception: '2015-05-28',
    holdings: [{ symbol: 'XBI', name: 'Short Biotech (3x)', weight: 100 }],
    sectors: [{ name: 'Leveraged Inverse', weight: 100, color: '#ef4444' }],
  },
  NAIL: {
    fullName: 'Direxion Daily Homebuilders & Supplies Bull 3X Shares',
    issuer: 'Direxion',
    expenseRatio: 0.95,
    aum: '$0.8B',
    index: '3x Leveraged Dow Jones U.S. Select Home Construction',
    category: 'Leveraged',
    inception: '2015-08-19',
    holdings: [{ symbol: 'ITB', name: 'Long Homebuilders (3x)', weight: 100 }],
    sectors: [{ name: 'Leveraged Long', weight: 100, color: '#22c55e' }],
  },
  BULZ: {
    fullName: 'MicroSectors Solactive FANG & Innovation 3X Leveraged ETN',
    issuer: 'Bank of Montreal',
    expenseRatio: 0.95,
    aum: '$0.6B',
    index: '3x Leveraged Solactive FANG & Innovation',
    category: 'Leveraged',
    inception: '2021-03-26',
    holdings: [{ symbol: 'FANG+', name: 'Long FANG & Innovation (3x)', weight: 100 }],
    sectors: [{ name: 'Leveraged Long', weight: 100, color: '#22c55e' }],
  },
  UVXY: {
    fullName: 'ProShares Ultra VIX Short-Term Futures ETF',
    issuer: 'ProShares',
    expenseRatio: 0.95,
    aum: '$0.8B',
    index: '1.5x Leveraged S&P 500 VIX Short-Term Futures',
    category: 'Leveraged',
    inception: '2011-10-03',
    holdings: [{ symbol: 'VIX', name: 'VIX Short-Term Futures (1.5x)', weight: 100 }],
    sectors: [{ name: 'Volatility', weight: 100, color: '#a78bfa' }],
  },
  SVXY: {
    fullName: 'ProShares Short VIX Short-Term Futures ETF',
    issuer: 'ProShares',
    expenseRatio: 0.95,
    aum: '$0.5B',
    index: '-0.5x S&P 500 VIX Short-Term Futures',
    category: 'Leveraged Inverse',
    inception: '2011-10-03',
    holdings: [{ symbol: 'VIX', name: 'Short VIX Short-Term Futures (-0.5x)', weight: 100 }],
    sectors: [{ name: 'Inverse Volatility', weight: 100, color: '#f43f5e' }],
  },

  // ── International ETFs ────────────────────────────────────────────────────────
  EFA: {
    fullName: 'iShares MSCI EAFE ETF',
    issuer: 'BlackRock',
    expenseRatio: 0.32,
    aum: '$48B',
    index: 'MSCI EAFE (Developed Markets ex-US & Canada)',
    category: 'International',
    inception: '2001-08-14',
    holdings: [
      { symbol: 'NESN', name: 'Nestlé SA', weight: 1.8 },
      { symbol: 'NOVO', name: 'Novo Nordisk', weight: 1.7 },
      { symbol: 'ASML', name: 'ASML Holding', weight: 1.5 },
      { symbol: 'ROG',  name: 'Roche Holding', weight: 1.2 },
    ],
    sectors: [
      { name: 'Financials', weight: 22, color: '#6366f1' },
      { name: 'Industrials', weight: 16, color: '#22c55e' },
      { name: 'Consumer', weight: 13, color: '#f59e0b' },
      { name: 'Healthcare', weight: 12, color: '#ec4899' },
      { name: 'Other', weight: 37, color: '#6b7280' },
    ],
  },
  EEM: {
    fullName: 'iShares MSCI Emerging Markets ETF',
    issuer: 'BlackRock',
    expenseRatio: 0.70,
    aum: '$18B',
    index: 'MSCI Emerging Markets',
    category: 'International',
    inception: '2003-04-07',
    holdings: [
      { symbol: 'TSM',    name: 'Taiwan Semiconductor', weight: 6.2 },
      { symbol: '700.HK', name: 'Tencent Holdings', weight: 4.1 },
      { symbol: 'BABA',   name: 'Alibaba Group', weight: 2.8 },
      { symbol: '005930', name: 'Samsung Electronics', weight: 2.5 },
    ],
    sectors: [
      { name: 'Tech', weight: 28, color: '#6366f1' },
      { name: 'Financials', weight: 22, color: '#22c55e' },
      { name: 'Consumer', weight: 14, color: '#f59e0b' },
      { name: 'Energy', weight: 8, color: '#ef4444' },
      { name: 'Other', weight: 28, color: '#6b7280' },
    ],
  },
  VEU: {
    fullName: 'Vanguard FTSE All-World ex-US ETF',
    issuer: 'Vanguard',
    expenseRatio: 0.07,
    aum: '$35B',
    index: 'FTSE All-World ex US',
    category: 'International',
    inception: '2007-03-02',
    holdings: [
      { symbol: 'TSM',  name: 'Taiwan Semiconductor', weight: 2.4 },
      { symbol: 'NOVO', name: 'Novo Nordisk', weight: 1.8 },
      { symbol: 'ASML', name: 'ASML Holding', weight: 1.4 },
      { symbol: 'NESN', name: 'Nestlé SA', weight: 1.3 },
    ],
    sectors: [
      { name: 'Financials', weight: 21, color: '#6366f1' },
      { name: 'Tech', weight: 18, color: '#22c55e' },
      { name: 'Industrials', weight: 14, color: '#f59e0b' },
      { name: 'Consumer', weight: 12, color: '#ec4899' },
      { name: 'Other', weight: 35, color: '#6b7280' },
    ],
  },
  VWO: {
    fullName: 'Vanguard FTSE Emerging Markets ETF',
    issuer: 'Vanguard',
    expenseRatio: 0.08,
    aum: '$80B',
    index: 'FTSE Emerging Markets All Cap China A Inclusion',
    category: 'International',
    inception: '2005-03-04',
    holdings: [
      { symbol: 'TSM',    name: 'Taiwan Semiconductor', weight: 8.3 },
      { symbol: '700.HK', name: 'Tencent Holdings', weight: 3.9 },
      { symbol: '005930', name: 'Samsung Electronics', weight: 3.0 },
      { symbol: 'BABA',   name: 'Alibaba Group', weight: 2.1 },
    ],
    sectors: [
      { name: 'Tech', weight: 26, color: '#6366f1' },
      { name: 'Financials', weight: 24, color: '#22c55e' },
      { name: 'Consumer', weight: 13, color: '#f59e0b' },
      { name: 'Materials', weight: 8, color: '#ec4899' },
      { name: 'Other', weight: 29, color: '#6b7280' },
    ],
  },
  IEFA: {
    fullName: 'iShares Core MSCI EAFE ETF',
    issuer: 'BlackRock',
    expenseRatio: 0.07,
    aum: '$93B',
    index: 'MSCI EAFE IMI',
    category: 'International',
    inception: '2012-10-18',
    holdings: [
      { symbol: 'NOVO', name: 'Novo Nordisk', weight: 2.1 },
      { symbol: 'NESN', name: 'Nestlé SA', weight: 1.9 },
      { symbol: 'ASML', name: 'ASML Holding', weight: 1.6 },
      { symbol: 'ROG',  name: 'Roche Holding', weight: 1.3 },
    ],
    sectors: [
      { name: 'Financials', weight: 20, color: '#6366f1' },
      { name: 'Industrials', weight: 17, color: '#22c55e' },
      { name: 'Consumer', weight: 14, color: '#f59e0b' },
      { name: 'Healthcare', weight: 12, color: '#ec4899' },
      { name: 'Other', weight: 37, color: '#6b7280' },
    ],
  },
  VGK: {
    fullName: 'Vanguard FTSE Europe ETF',
    issuer: 'Vanguard',
    expenseRatio: 0.09,
    aum: '$18B',
    index: 'FTSE Developed Europe All Cap',
    category: 'International',
    inception: '2005-03-04',
    holdings: [
      { symbol: 'ASML', name: 'ASML Holding', weight: 3.1 },
      { symbol: 'NESN', name: 'Nestlé SA', weight: 2.9 },
      { symbol: 'NOVO', name: 'Novo Nordisk', weight: 2.8 },
      { symbol: 'ROG',  name: 'Roche Holding', weight: 2.0 },
    ],
    sectors: [
      { name: 'Financials', weight: 18, color: '#6366f1' },
      { name: 'Industrials', weight: 17, color: '#22c55e' },
      { name: 'Healthcare', weight: 15, color: '#ec4899' },
      { name: 'Consumer', weight: 13, color: '#f59e0b' },
      { name: 'Other', weight: 37, color: '#6b7280' },
    ],
  },
  EWJ: {
    fullName: 'iShares MSCI Japan ETF',
    issuer: 'BlackRock',
    expenseRatio: 0.50,
    aum: '$12B',
    index: 'MSCI Japan',
    category: 'International',
    inception: '1996-03-12',
    holdings: [
      { symbol: '7203', name: 'Toyota Motor', weight: 4.5 },
      { symbol: '6758', name: 'Sony Group', weight: 3.8 },
      { symbol: '8306', name: 'Mitsubishi UFJ', weight: 3.1 },
      { symbol: '6861', name: 'Keyence Corp', weight: 2.7 },
    ],
    sectors: [
      { name: 'Industrials', weight: 22, color: '#6366f1' },
      { name: 'Consumer', weight: 20, color: '#22c55e' },
      { name: 'Tech', weight: 16, color: '#f59e0b' },
      { name: 'Financials', weight: 14, color: '#ec4899' },
      { name: 'Other', weight: 28, color: '#6b7280' },
    ],
  },
  EWZ: {
    fullName: 'iShares MSCI Brazil ETF',
    issuer: 'BlackRock',
    expenseRatio: 0.59,
    aum: '$5B',
    index: 'MSCI Brazil 25/50',
    category: 'International',
    inception: '2000-07-10',
    holdings: [
      { symbol: 'VALE3', name: 'Vale S.A.', weight: 10.2 },
      { symbol: 'PETR4', name: 'Petrobras', weight: 8.5 },
      { symbol: 'ITUB4', name: 'Itaú Unibanco', weight: 7.3 },
      { symbol: 'BBDC4', name: 'Banco Bradesco', weight: 4.9 },
    ],
    sectors: [
      { name: 'Financials', weight: 28, color: '#6366f1' },
      { name: 'Materials', weight: 22, color: '#22c55e' },
      { name: 'Energy', weight: 18, color: '#f59e0b' },
      { name: 'Utilities', weight: 9, color: '#ec4899' },
      { name: 'Other', weight: 23, color: '#6b7280' },
    ],
  },
  FXI: {
    fullName: 'iShares China Large-Cap ETF',
    issuer: 'BlackRock',
    expenseRatio: 0.74,
    aum: '$6B',
    index: 'FTSE China 50',
    category: 'International',
    inception: '2004-10-05',
    holdings: [
      { symbol: '700.HK', name: 'Tencent Holdings', weight: 9.8 },
      { symbol: 'BABA',   name: 'Alibaba Group', weight: 8.4 },
      { symbol: '3988',   name: 'Bank of China', weight: 5.2 },
      { symbol: '939',    name: 'China Construction Bank', weight: 4.8 },
    ],
    sectors: [
      { name: 'Financials', weight: 33, color: '#6366f1' },
      { name: 'Tech', weight: 22, color: '#22c55e' },
      { name: 'Consumer', weight: 16, color: '#f59e0b' },
      { name: 'Energy', weight: 7, color: '#ef4444' },
      { name: 'Other', weight: 22, color: '#6b7280' },
    ],
  },
  IEMG: {
    fullName: 'iShares Core MSCI Emerging Markets ETF',
    issuer: 'BlackRock',
    expenseRatio: 0.09,
    aum: '$70B',
    index: 'MSCI Emerging Markets Investable Market',
    category: 'International',
    inception: '2012-10-18',
    holdings: [
      { symbol: 'TSM',    name: 'Taiwan Semiconductor', weight: 7.4 },
      { symbol: '700.HK', name: 'Tencent Holdings', weight: 4.0 },
      { symbol: '005930', name: 'Samsung Electronics', weight: 3.1 },
      { symbol: 'BABA',   name: 'Alibaba Group', weight: 2.3 },
    ],
    sectors: [
      { name: 'Tech', weight: 27, color: '#6366f1' },
      { name: 'Financials', weight: 22, color: '#22c55e' },
      { name: 'Consumer', weight: 14, color: '#f59e0b' },
      { name: 'Materials', weight: 7, color: '#ec4899' },
      { name: 'Other', weight: 30, color: '#6b7280' },
    ],
  },

  // ── Country-specific International ETFs ──────────────────────────────────────
  INDA: {
    fullName: 'iShares MSCI India ETF',
    issuer: 'BlackRock',
    expenseRatio: 0.64,
    aum: '$9B',
    index: 'MSCI India',
    category: 'International',
    inception: '2012-02-02',
    country: 'India 🇮🇳',
    holdings: [
      { symbol: 'RELIANCE', name: 'Reliance Industries', weight: 10.2 },
      { symbol: 'HDFCBANK', name: 'HDFC Bank', weight: 8.5 },
      { symbol: 'INFY',     name: 'Infosys', weight: 6.8 },
      { symbol: 'ICICIBANK',name: 'ICICI Bank', weight: 5.9 },
    ],
    sectors: [
      { name: 'Financials', weight: 27, color: '#6366f1' },
      { name: 'Tech', weight: 18, color: '#22c55e' },
      { name: 'Energy', weight: 14, color: '#f59e0b' },
      { name: 'Consumer', weight: 11, color: '#ec4899' },
      { name: 'Other', weight: 30, color: '#6b7280' },
    ],
  },
  MCHI: {
    fullName: 'iShares MSCI China ETF',
    issuer: 'BlackRock',
    expenseRatio: 0.57,
    aum: '$6B',
    index: 'MSCI China',
    category: 'International',
    inception: '2011-03-29',
    country: 'China 🇨🇳',
    holdings: [
      { symbol: '700.HK', name: 'Tencent Holdings', weight: 10.4 },
      { symbol: 'BABA',   name: 'Alibaba Group', weight: 9.1 },
      { symbol: 'BIDU',   name: 'Baidu', weight: 3.8 },
      { symbol: 'JD',     name: 'JD.com', weight: 3.2 },
    ],
    sectors: [
      { name: 'Tech', weight: 34, color: '#6366f1' },
      { name: 'Consumer', weight: 22, color: '#22c55e' },
      { name: 'Financials', weight: 18, color: '#f59e0b' },
      { name: 'Healthcare', weight: 6, color: '#ec4899' },
      { name: 'Other', weight: 20, color: '#6b7280' },
    ],
  },
  KWEB: {
    fullName: 'KraneShares CSI China Internet ETF',
    issuer: 'KraneShares',
    expenseRatio: 0.69,
    aum: '$4B',
    index: 'CSI Overseas China Internet',
    category: 'International',
    inception: '2013-07-31',
    country: 'China 🇨🇳',
    holdings: [
      { symbol: '700.HK', name: 'Tencent Holdings', weight: 12.5 },
      { symbol: 'BABA',   name: 'Alibaba Group', weight: 11.2 },
      { symbol: 'JD',     name: 'JD.com', weight: 7.8 },
      { symbol: 'BIDU',   name: 'Baidu', weight: 6.4 },
    ],
    sectors: [
      { name: 'Internet', weight: 55, color: '#6366f1' },
      { name: 'E-Commerce', weight: 25, color: '#22c55e' },
      { name: 'Fintech', weight: 12, color: '#f59e0b' },
      { name: 'Other', weight: 8, color: '#6b7280' },
    ],
  },
  EWY: {
    fullName: 'iShares MSCI South Korea ETF',
    issuer: 'BlackRock',
    expenseRatio: 0.57,
    aum: '$3B',
    index: 'MSCI Korea 25/50',
    category: 'International',
    inception: '2000-05-09',
    country: 'South Korea 🇰🇷',
    holdings: [
      { symbol: '005930', name: 'Samsung Electronics', weight: 20.1 },
      { symbol: '000660', name: 'SK Hynix', weight: 6.8 },
      { symbol: '051910', name: 'LG Chem', weight: 4.2 },
      { symbol: '035420', name: 'NAVER', weight: 3.8 },
    ],
    sectors: [
      { name: 'Tech', weight: 34, color: '#6366f1' },
      { name: 'Industrials', weight: 18, color: '#22c55e' },
      { name: 'Consumer', weight: 14, color: '#f59e0b' },
      { name: 'Financials', weight: 12, color: '#ec4899' },
      { name: 'Other', weight: 22, color: '#6b7280' },
    ],
  },
  EWA: {
    fullName: 'iShares MSCI Australia ETF',
    issuer: 'BlackRock',
    expenseRatio: 0.50,
    aum: '$2B',
    index: 'MSCI Australia',
    category: 'International',
    inception: '1996-03-12',
    country: 'Australia 🇦🇺',
    holdings: [
      { symbol: 'BHP',  name: 'BHP Group', weight: 11.5 },
      { symbol: 'CBA',  name: 'Commonwealth Bank', weight: 9.2 },
      { symbol: 'CSL',  name: 'CSL Limited', weight: 7.1 },
      { symbol: 'NAB',  name: 'National Australia Bank', weight: 5.8 },
    ],
    sectors: [
      { name: 'Materials', weight: 26, color: '#6366f1' },
      { name: 'Financials', weight: 28, color: '#22c55e' },
      { name: 'Healthcare', weight: 10, color: '#f59e0b' },
      { name: 'Industrials', weight: 8, color: '#ec4899' },
      { name: 'Other', weight: 28, color: '#6b7280' },
    ],
  },
  EWT: {
    fullName: 'iShares MSCI Taiwan ETF',
    issuer: 'BlackRock',
    expenseRatio: 0.57,
    aum: '$6B',
    index: 'MSCI Taiwan 25/50',
    category: 'International',
    inception: '2000-06-20',
    country: 'Taiwan 🇹🇼',
    holdings: [
      { symbol: 'TSM',   name: 'Taiwan Semiconductor', weight: 24.5 },
      { symbol: '2317',  name: 'Hon Hai Precision', weight: 5.2 },
      { symbol: '2330',  name: 'MediaTek', weight: 4.8 },
      { symbol: '2454',  name: 'Largan Precision', weight: 2.1 },
    ],
    sectors: [
      { name: 'Tech', weight: 65, color: '#6366f1' },
      { name: 'Industrials', weight: 12, color: '#22c55e' },
      { name: 'Financials', weight: 10, color: '#f59e0b' },
      { name: 'Materials', weight: 7, color: '#ec4899' },
      { name: 'Other', weight: 6, color: '#6b7280' },
    ],
  },

  // ── Crypto Exposure ETFs ──────────────────────────────────────────────────────
  IBIT: {
    fullName: 'iShares Bitcoin Trust ETF',
    issuer: 'BlackRock',
    expenseRatio: 0.25,
    aum: '$54B',
    index: 'Spot Bitcoin',
    category: 'Crypto',
    inception: '2024-01-11',
    holdings: [{ symbol: 'BTC', name: 'Bitcoin (Spot)', weight: 100 }],
    sectors: [{ name: 'Bitcoin', weight: 100, color: '#f7931a' }],
  },
  FBTC: {
    fullName: 'Fidelity Wise Origin Bitcoin Fund',
    issuer: 'Fidelity',
    expenseRatio: 0.25,
    aum: '$19B',
    index: 'Spot Bitcoin',
    category: 'Crypto',
    inception: '2024-01-11',
    holdings: [{ symbol: 'BTC', name: 'Bitcoin (Spot)', weight: 100 }],
    sectors: [{ name: 'Bitcoin', weight: 100, color: '#f7931a' }],
  },
  GBTC: {
    fullName: 'Grayscale Bitcoin Trust ETF',
    issuer: 'Grayscale',
    expenseRatio: 1.50,
    aum: '$17B',
    index: 'Spot Bitcoin',
    category: 'Crypto',
    inception: '2024-01-11',
    holdings: [{ symbol: 'BTC', name: 'Bitcoin (Spot)', weight: 100 }],
    sectors: [{ name: 'Bitcoin', weight: 100, color: '#f7931a' }],
  },
  BITB: {
    fullName: 'Bitwise Bitcoin ETF',
    issuer: 'Bitwise',
    expenseRatio: 0.20,
    aum: '$4B',
    index: 'Spot Bitcoin',
    category: 'Crypto',
    inception: '2024-01-11',
    holdings: [{ symbol: 'BTC', name: 'Bitcoin (Spot)', weight: 100 }],
    sectors: [{ name: 'Bitcoin', weight: 100, color: '#f7931a' }],
  },
  BITO: {
    fullName: 'ProShares Bitcoin Strategy ETF',
    issuer: 'ProShares',
    expenseRatio: 0.95,
    aum: '$2B',
    index: 'Bitcoin Futures',
    category: 'Crypto',
    inception: '2021-10-18',
    holdings: [{ symbol: 'BTC', name: 'Bitcoin Futures (CME)', weight: 100 }],
    sectors: [{ name: 'Bitcoin Futures', weight: 100, color: '#f7931a' }],
  },
  ETHA: {
    fullName: 'iShares Ethereum Trust ETF',
    issuer: 'BlackRock',
    expenseRatio: 0.25,
    aum: '$3B',
    index: 'Spot Ethereum',
    category: 'Crypto',
    inception: '2024-07-23',
    holdings: [{ symbol: 'ETH', name: 'Ethereum (Spot)', weight: 100 }],
    sectors: [{ name: 'Ethereum', weight: 100, color: '#627eea' }],
  },
  MSTR: {
    fullName: 'MicroStrategy Incorporated',
    issuer: 'MicroStrategy',
    expenseRatio: 0,
    aum: '$80B',
    index: 'Bitcoin Proxy (Equity)',
    category: 'Crypto',
    inception: '1998-06-11',
    holdings: [{ symbol: 'BTC', name: 'Bitcoin Holdings (Proxy)', weight: 100 }],
    sectors: [{ name: 'Bitcoin (Equity Proxy)', weight: 100, color: '#f7931a' }],
  },
};
